### ISSUE TITLE
help with village editor

### ISSUE THREAD

**Issue by kiasilverfatalis** [oswarlan/Bravely-Default-Village-Editor#1]
hi, i used your editor, the latest version, i did all the steps to have the villagers added, but they don't show up in norande when i choose to build something. what can i do to fix this, or is it no longer working?

**Comment by oswarlan** [comment]
It should still work fine, since Bravely Default hasn't been updated in years. If the villagers aren't showing up, you'll have to double check you did every step properly.

**Comment by kiasilverfatalis** [comment]
I did the export, or save through jksm, for some reason, there's no export option available anymore, just saving the file. When i load it through the app, after saving it, it shows the number of villagers i selected, but it doesn't show them in game, bow exactly do i need to do this? I tried using savedata filer, but that looks too complicated, to find the saves on there

**Comment by oswarlan** [comment]
With both save apps, there is an Export and an Import option, you just have to select the game, and then the correct option. If you've already edited the save, then you just need to import.

**Comment by kiasilverfatalis** [comment]
i got it figured out, i appreciate you makig this awesome editor
